// src/lib/mockData.js

export const ALL_CARDS = [
    { id: 'hog-rider', name: 'Hog Rider', type: 'Troop', elixir: 4 },
    { id: 'log', name: 'The Log', type: 'Spell', elixir: 2 },
    { id: 'goblin-barrel', name: 'Goblin Barrel', type: 'Spell', elixir: 3 },
    { id: 'princess', name: 'Princess', type: 'Troop', elixir: 3 },
    { id: 'knight', name: 'Knight', type: 'Troop', elixir: 3 },
    { id: 'goblin-gang', name: 'Goblin Gang', type: 'Troop', elixir: 3 },
    { id: 'inferno-tower', name: 'Inferno Tower', type: 'Building', elixir: 5 },
    { id: 'ice-spirit', name: 'Ice Spirit', type: 'Troop', elixir: 1 },
    { id: 'pekka', name: 'P.E.K.K.A', type: 'Troop', elixir: 7 },
    { id: 'battle-ram', name: 'Battle Ram', type: 'Troop', elixir: 4 },
    { id: 'bandit', name: 'Bandit', type: 'Troop', elixir: 3 },
    { id: 'royal-ghost', name: 'Royal Ghost', type: 'Troop', elixir: 3 },
    { id: 'magic-archer', name: 'Magic Archer', type: 'Troop', elixir: 4 },
    { id: 'zap', name: 'Zap', type: 'Spell', elixir: 2 },
    { id: 'poison', name: 'Poison', type: 'Spell', elixir: 4 },
    { id: 'x-bow', name: 'X-Bow', type: 'Building', elixir: 6 },
    { id: 'archers', name: 'Archers', type: 'Troop', elixir: 3 },
    { id: 'skeletons', name: 'Skeletons', type: 'Troop', elixir: 1 },
    { id: 'tesla', name: 'Tesla', type: 'Building', elixir: 4 },
    { id: 'fireball', name: 'Fireball', type: 'Spell', elixir: 4 },
    { id: 'electro-wizard', name: 'Electro Wizard', type: 'Troop', elixir: 4 },
    { id: 'rocket', name: 'Rocket', type: 'Spell', elixir: 6 },
    { id: 'musketeer', name: 'Musketeer', type: 'Troop', elixir: 4 },
    { id: 'ice-golem', name: 'Ice Golem', type: 'Troop', elixir: 2 },
    { id: 'cannon', name: 'Cannon', type: 'Building', elixir: 3 },
    { id: 'miner', name: 'Miner', type: 'Troop', elixir: 3 },
    { id: 'wall-breakers', name: 'Wall Breakers', type: 'Troop', elixir: 2 },
    { id: 'bomb-tower', name: 'Bomb Tower', type: 'Building', elixir: 4 },
    { id: 'valkyrie', name: 'Valkyrie', type: 'Troop', elixir: 4 },
    { id: 'golem', name: 'Golem', type: 'Troop', elixir: 8 },
    { id: 'night-witch', name: 'Night Witch', type: 'Troop', elixir: 4 },
    { id: 'lumberjack', name: 'Lumberjack', type: 'Troop', elixir: 4 },
    { id: 'balloon', name: 'Balloon', type: 'Troop', elixir: 5 },
    { id: 'lava-hound', name: 'Lava Hound', type: 'Troop', elixir: 7 },
    { id: 'flying-machine', name: 'Flying Machine', type: 'Troop', elixir: 4 },
    { id: 'arrows', name: 'Arrows', type: 'Spell', elixir: 3 },
    { id: 'tornado', name: 'Tornado', type: 'Spell', elixir: 3 },
    { id: 'baby-dragon', name: 'Baby Dragon', type: 'Troop', elixir: 4 },
    { id: 'bowler', name: 'Bowler', type: 'Troop', elixir: 5 },
    { id: 'graveyard', name: 'Graveyard', type: 'Spell', elixir: 5 },
    { id: 'mega-minion', name: 'Mega Minion', type: 'Troop', elixir: 3 },
    { id: 'royal-giant', name: 'Royal Giant', type: 'Troop', elixir: 6 },
    { id: 'fisherman', name: 'Fisherman', type: 'Troop', elixir: 3 },
    { id: 'hunter', name: 'Hunter', type: 'Troop', elixir: 4 },
    { id: 'zappies', name: 'Zappies', type: 'Troop', elixir: 4 },
    { id: 'earthquake', name: 'Earthquake', type: 'Spell', elixir: 3 },
    { id: 'royal-delivery', name: 'Royal Delivery', type: 'Spell', elixir: 3 },
    { id: 'skeleton-army', name: 'Skeleton Army', type: 'Troop', elixir: 3 },
    { id: 'clone', name: 'Clone', type: 'Spell', elixir: 3 },
];

export const MOCK_DECKS = [
    { id: 'deck-1', name: 'Classic Log Bait', archetype: 'LogBait', winRate: 52.4, usageRate: 11.2, cards: ['goblin-barrel', 'princess', 'knight', 'goblin-gang', 'inferno-tower', 'ice-spirit', 'log', 'rocket'], dateAdded: '2023-10-01' },
    { id: 'deck-2', name: 'PEKKA Bridge Spam', archetype: 'Bridge Spam', winRate: 54.1, usageRate: 8.5, cards: ['pekka', 'battle-ram', 'bandit', 'royal-ghost', 'magic-archer', 'electro-wizard', 'zap', 'poison'], dateAdded: '2023-10-05' },
    { id: 'deck-3', name: 'X-Bow 2.9 Cycle', archetype: 'Siege', winRate: 50.8, usageRate: 5.4, cards: ['x-bow', 'archers', 'knight', 'skeletons', 'tesla', 'ice-spirit', 'fireball', 'log'], dateAdded: '2023-10-10' },
    { id: 'deck-4', name: 'Hog 2.6 Cycle', archetype: 'Cycle', winRate: 49.5, usageRate: 14.1, cards: ['hog-rider', 'musketeer', 'ice-golem', 'skeletons', 'cannon', 'ice-spirit', 'fireball', 'log'], dateAdded: '2023-10-12' },
    { id: 'deck-5', name: 'Miner Wall Breakers', archetype: 'Control', winRate: 53.2, usageRate: 7.8, cards: ['miner', 'wall-breakers', 'magic-archer', 'valkyrie', 'bomb-tower', 'log', 'tornado', 'skeletons'], dateAdded: '2023-10-15' },
    { id: 'deck-6', name: 'Golem Beatdown', archetype: 'Beatdown', winRate: 55.6, usageRate: 6.2, cards: ['golem', 'night-witch', 'lumberjack', 'baby-dragon', 'mega-minion', 'tornado', 'zap', 'lightning'], dateAdded: '2023-10-16' },
    { id: 'deck-7', name: 'LavaLoon', archetype: 'Beatdown', winRate: 56.1, usageRate: 5.1, cards: ['lava-hound', 'balloon', 'mega-minion', 'skeleton-dragons', 'flying-machine', 'arrows', 'zap', 'tombstone'], dateAdded: '2023-10-18' },
    { id: 'deck-8', name: 'Splashyard', archetype: 'Control', winRate: 51.5, usageRate: 9.3, cards: ['graveyard', 'bowler', 'baby-dragon', 'ice-wizard', 'valkyrie', 'tornado', 'poison', 'barbarian-barrel'], dateAdded: '2023-10-20' },
    { id: 'deck-9', name: 'RG Fisherman', archetype: 'Control', winRate: 54.8, usageRate: 8.9, cards: ['royal-giant', 'fisherman', 'hunter', 'zappies', 'royal-ghost', 'electro-spirit', 'fireball', 'log'], dateAdded: '2023-10-22' },
    { id: 'deck-10', name: 'Hog Earthquake', archetype: 'Cycle', winRate: 50.2, usageRate: 10.5, cards: ['hog-rider', 'earthquake', 'firecracker', 'valkyrie', 'bomb-tower', 'skeletons', 'log', 'ice-spirit'], dateAdded: '2023-10-25' },
    { id: 'deck-11', name: 'Giant Graveyard', archetype: 'Beatdown', winRate: 52.8, usageRate: 4.2, cards: ['giant', 'graveyard', 'musketeer', 'skeleton-army', 'bats', 'snowball', 'arrows', 'dark-prince'], dateAdded: '2023-10-28' },
    { id: 'deck-12', name: 'LumberLoon Freeze', archetype: 'Aggro', winRate: 51.1, usageRate: 6.8, cards: ['lumberjack', 'balloon', 'freeze', 'bowler', 'inferno-dragon', 'electro-dragon', 'tornado', 'barbarian-barrel'], dateAdded: '2023-11-01' },
];

export const MOCK_PLAYERS = [
    { rank: 1, name: 'Mohamed Light', tag: '#YUGJY82G', trophies: 8400, region: 'Egypt' },
    { rank: 2, name: 'Morten', tag: '#V80C', trophies: 8350, region: 'Germany' },
    { rank: 3, name: 'Surg TS', tag: '#VVC9Q9', trophies: 8300, region: 'Brazil' },
    { rank: 4, name: 'Pompeyo4', tag: '#Q9Y8C', trophies: 8250, region: 'Mexico' },
    { rank: 5, name: 'Lucas', tag: '#VQRRQV', trophies: 8210, region: 'Brazil' },
];

export const MOCK_CLANS = [
    { rank: 1, name: 'Tribe Gaming', tag: '#QYPJRC0', trophies: 95000, region: 'International', members: 50 },
    { rank: 2, name: 'SK Gaming', tag: '#PQR92JL', trophies: 94500, region: 'Germany', members: 49 },
    { rank: 3, name: 'Team Liquid', tag: '#CG98LL', trophies: 93800, region: 'International', members: 48 },
    { rank: 4, name: 'Nova Esports', tag: '#P8G9JQ', trophies: 92000, region: 'China', members: 50 },
    { rank: 5, name: 'Spacestation', tag: '#Q202R9C', trophies: 91500, region: 'USA', members: 50 },
];
