const fs = require('fs');

let content = fs.readFileSync('src/lib/mockData.js', 'utf8');

// Find the last deck entry and insert 100 decks after it before the ]
const anchor = "deck-70', name: 'Meta Bait V50'";
const anchorIdx = content.indexOf(anchor);
if (anchorIdx === -1) { console.error('anchor not found'); process.exit(1); }

// Find the end of this line (the closing } or })
let lineEnd = content.indexOf('\n', anchorIdx);
if (lineEnd === -1) lineEnd = content.length;

// Decks to insert - 100 new decks with champions/evolutions
const newDecks = [
    `    { id: 'deck-71', name: 'Pequeno Príncipe Log Bait', archetype: 'Bait', winRate: 55.2, usageRate: 9.1, cards: ['little-prince','goblin-barrel','princess','goblin-gang','inferno-tower','ice-spirit','the-log','rocket'], dateAdded: '2024-01-01' }`,
    `    { id: 'deck-72', name: 'Monge Golem Beatdown', archetype: 'Beatdown', winRate: 56.3, usageRate: 5.8, cards: ['monk','golem','night-witch','baby-dragon','mega-minion','tornado','zap','lightning'], dateAdded: '2024-01-02' }`,
    `    { id: 'deck-73', name: 'Rainha Arqueira Hog Cycle', archetype: 'Cycle', winRate: 54.7, usageRate: 10.2, cards: ['archer-queen','hog-rider','musketeer','ice-golem','skeletons','cannon','fireball','the-log'], dateAdded: '2024-01-03' }`,
    `    { id: 'deck-74', name: 'Rei Esqueleto Graveyard', archetype: 'Control', winRate: 53.9, usageRate: 7.4, cards: ['skeleton-king','graveyard','bowler','valkyrie','tornado','poison','barbarian-barrel','tombstone'], dateAdded: '2024-01-04' }`,
    `    { id: 'deck-75', name: 'Cavaleiro Dourado Bridge Spam', archetype: 'Bridge Spam', winRate: 57.1, usageRate: 6.5, cards: ['golden-knight','pekka','battle-ram','electro-wizard','magic-archer','royal-ghost','zap','poison'], dateAdded: '2024-01-05' }`,
    `    { id: 'deck-76', name: 'Mineiro Poderoso Wall Breakers', archetype: 'Control', winRate: 53.5, usageRate: 8.1, cards: ['mighty-miner','wall-breakers','magic-archer','valkyrie','bomb-tower','the-log','tornado','skeletons'], dateAdded: '2024-01-06' }`,
    `    { id: 'deck-77', name: 'Evo Fogueteira Hog', archetype: 'Cycle', winRate: 55.8, usageRate: 11.3, cards: ['hog-rider','firecracker-ev1','ice-golem','cannon','musketeer','fireball','the-log','ice-spirit'], dateAdded: '2024-01-07' }`,
    `    { id: 'deck-78', name: 'Evo Cavaleiro X-Bow', archetype: 'Siege', winRate: 52.4, usageRate: 6.9, cards: ['x-bow','knight-ev1','archers','skeletons','tesla','ice-spirit','fireball','the-log'], dateAdded: '2024-01-08' }`,
    `    { id: 'deck-79', name: 'Evo Bárbaros Gigante Real', archetype: 'Beatdown', winRate: 51.7, usageRate: 7.2, cards: ['royal-giant','barbarians-ev1','musketeer','flying-machine','zappies','royal-delivery','fireball','the-log'], dateAdded: '2024-01-09' }`,
    `    { id: 'deck-80', name: 'Evo Esqueletos Mineiro', archetype: 'Cycle', winRate: 54.1, usageRate: 9.8, cards: ['miner','skeletons-ev1','wall-breakers','magic-archer','ice-golem','bomb-tower','the-log','poison'], dateAdded: '2024-01-10' }`,
    `    { id: 'deck-81', name: 'Evo Gigante Real Beatdown', archetype: 'Beatdown', winRate: 53.2, usageRate: 5.4, cards: ['royal-giant-ev1','electro-wizard','hunter','zappies','royal-ghost','electro-spirit','fireball','the-log'], dateAdded: '2024-01-11' }`,
    `    { id: 'deck-82', name: 'Evo Valquíria Golem', archetype: 'Beatdown', winRate: 56.0, usageRate: 4.7, cards: ['golem','valkyrie-ev1','lumberjack','night-witch','baby-dragon','tornado','zap','lightning'], dateAdded: '2024-01-12' }`,
    `    { id: 'deck-83', name: 'Evo Arqueiras LavaLoon', archetype: 'Beatdown', winRate: 57.4, usageRate: 4.1, cards: ['lava-hound','balloon','archers-ev1','mega-minion','flying-machine','arrows','zap','tombstone'], dateAdded: '2024-01-13' }`,
    `    { id: 'deck-84', name: 'Evo Morcegos Splashyard', archetype: 'Control', winRate: 52.6, usageRate: 8.3, cards: ['graveyard','bowler','baby-dragon','bats-ev1','valkyrie','tornado','poison','barbarian-barrel'], dateAdded: '2024-01-14' }`,
    `    { id: 'deck-85', name: 'Evo Morteiro Bait', archetype: 'Siege', winRate: 50.9, usageRate: 5.2, cards: ['mortar-ev1','miner','minion-horde','goblin-gang','spear-goblins','bats','the-log','fireball'], dateAdded: '2024-01-15' }`,
    `    { id: 'deck-86', name: 'Evo Rompedores Controle', archetype: 'Control', winRate: 53.8, usageRate: 7.6, cards: ['miner','wall-breakers-ev1','magic-archer','valkyrie','bomb-tower','the-log','arrows','skeletons'], dateAdded: '2024-01-16' }`,
    `    { id: 'deck-87', name: 'Rei Esqueleto Golem', archetype: 'Beatdown', winRate: 55.5, usageRate: 5.9, cards: ['skeleton-king','golem','night-witch','lumberjack','mega-minion','tornado','zap','lightning'], dateAdded: '2024-01-17' }`,
    `    { id: 'deck-88', name: 'Rainha Arqueira Earthquake', archetype: 'Cycle', winRate: 54.9, usageRate: 10.5, cards: ['archer-queen','hog-rider','earthquake','the-log','royal-delivery','cannon','skeletons','ice-spirit'], dateAdded: '2024-01-18' }`,
    `    { id: 'deck-89', name: 'Monge LavaLoon', archetype: 'Beatdown', winRate: 56.8, usageRate: 4.3, cards: ['monk','lava-hound','balloon','mega-minion','skeleton-dragons','flying-machine','arrows','zap'], dateAdded: '2024-01-19' }`,
    `    { id: 'deck-90', name: 'Pequeno Príncipe X-Bow', archetype: 'Siege', winRate: 51.3, usageRate: 6.7, cards: ['x-bow','little-prince','archers','skeletons','tesla','ice-spirit','fireball','the-log'], dateAdded: '2024-01-20' }`,
    `    { id: 'deck-91', name: 'Cavaleiro Dourado LumberLoon', archetype: 'Aggro', winRate: 55.1, usageRate: 5.5, cards: ['golden-knight','lumberjack','balloon','freeze','bowler','inferno-dragon','tornado','barbarian-barrel'], dateAdded: '2024-01-21' }`,
    `    { id: 'deck-92', name: 'Mineiro Poderoso Mortar', archetype: 'Siege', winRate: 52.7, usageRate: 5.0, cards: ['mortar','mighty-miner','miner','bats','goblin-gang','spear-goblins','the-log','fireball'], dateAdded: '2024-01-22' }`,
    `    { id: 'deck-93', name: 'Evo Espírito de Gelo Hog', archetype: 'Cycle', winRate: 50.8, usageRate: 12.1, cards: ['hog-rider','ice-spirit-ev1','musketeer','ice-golem','cannon','fireball','the-log','skeletons'], dateAdded: '2024-01-23' }`,
    `    { id: 'deck-94', name: 'Golem Pequeno Príncipe', archetype: 'Beatdown', winRate: 56.6, usageRate: 5.2, cards: ['golem','little-prince','night-witch','baby-dragon','lumberjack','tornado','zap','lightning'], dateAdded: '2024-01-24' }`,
    `    { id: 'deck-95', name: 'Evo Recrutas Reais Control', archetype: 'Control', winRate: 53.4, usageRate: 6.3, cards: ['royal-recruits-ev1','flying-machine','zappies','goblin-cage','barbarian-barrel','royal-delivery','arrows','the-log'], dateAdded: '2024-01-25' }`,
    `    { id: 'deck-96', name: 'Hog Rider Evo Bombardeiro', archetype: 'Cycle', winRate: 54.3, usageRate: 9.0, cards: ['hog-rider','bomber-ev1','valkyrie','cannon','skeletons','ice-spirit','fireball','the-log'], dateAdded: '2024-01-26' }`,
    `    { id: 'deck-97', name: 'Evo Gigante Goblin Sparky', archetype: 'Beatdown', winRate: 54.9, usageRate: 4.8, cards: ['goblin-giant-ev1','sparky','dark-prince','electro-wizard','mega-minion','zap','arrows','lightning'], dateAdded: '2024-01-27' }`,
    `    { id: 'deck-98', name: 'Evo Goblins Lança Bait', archetype: 'Bait', winRate: 52.1, usageRate: 7.8, cards: ['goblin-barrel','spear-goblins-ev1','princess','knight','inferno-tower','ice-spirit','the-log','rocket'], dateAdded: '2024-01-28' }`,
    `    { id: 'deck-99', name: 'Monge Hog Cycle', archetype: 'Cycle', winRate: 55.3, usageRate: 8.7, cards: ['monk','hog-rider','ice-golem','skeletons','cannon','ice-spirit','fireball','the-log'], dateAdded: '2024-02-01' }`,
    `    { id: 'deck-100', name: 'Rainha Arqueira PEKKA', archetype: 'Bridge Spam', winRate: 56.2, usageRate: 6.1, cards: ['archer-queen','pekka','battle-ram','bandit','magic-archer','electro-wizard','zap','poison'], dateAdded: '2024-02-02' }`,
    `    { id: 'deck-101', name: 'Rei Esqueleto Cycle', archetype: 'Cycle', winRate: 53.1, usageRate: 9.4, cards: ['skeleton-king','hog-rider','musketeer','ice-golem','skeletons','cannon','fireball','the-log'], dateAdded: '2024-02-03' }`,
    `    { id: 'deck-102', name: 'Mineiro Evo Fogueteira', archetype: 'Control', winRate: 54.6, usageRate: 8.5, cards: ['miner','firecracker-ev1','valkyrie','bomb-tower','goblin-gang','the-log','rocket','skeletons'], dateAdded: '2024-02-04' }`,
    `    { id: 'deck-103', name: 'Cavaleiro Dourado Golem', archetype: 'Beatdown', winRate: 57.3, usageRate: 4.5, cards: ['golden-knight','golem','baby-dragon','mega-minion','night-witch','tornado','zap','lightning'], dateAdded: '2024-02-05' }`,
    `    { id: 'deck-104', name: 'Evo Cavaleiro Hog', archetype: 'Cycle', winRate: 52.9, usageRate: 8.9, cards: ['hog-rider','knight-ev1','musketeer','ice-golem','cannon','ice-spirit','fireball','the-log'], dateAdded: '2024-02-06' }`,
    `    { id: 'deck-105', name: 'LavaLoon Evo Morcegos', archetype: 'Beatdown', winRate: 57.5, usageRate: 4.2, cards: ['lava-hound','balloon','bats-ev1','mega-minion','flying-machine','arrows','zap','tombstone'], dateAdded: '2024-02-07' }`,
    `    { id: 'deck-106', name: 'Splashyard Evo Bárbaros', archetype: 'Control', winRate: 53.7, usageRate: 7.1, cards: ['graveyard','barbarians-ev1','bowler','baby-dragon','ice-wizard','tornado','poison','barbarian-barrel'], dateAdded: '2024-02-08' }`,
    `    { id: 'deck-107', name: 'Pequeno Príncipe Balloon', archetype: 'Aggro', winRate: 55.9, usageRate: 5.6, cards: ['little-prince','balloon','lumberjack','freeze','bowler','inferno-dragon','electro-dragon','barbarian-barrel'], dateAdded: '2024-02-09' }`,
    `    { id: 'deck-108', name: 'Evo Esqueletos Graveyard', archetype: 'Control', winRate: 52.3, usageRate: 8.2, cards: ['graveyard','skeletons-ev1','bowler','baby-dragon','ice-wizard','tornado','poison','barbarian-barrel'], dateAdded: '2024-02-10' }`,
    `    { id: 'deck-109', name: 'Monge X-Bow', archetype: 'Siege', winRate: 51.8, usageRate: 6.4, cards: ['x-bow','monk','archers','knight','tesla','ice-spirit','fireball','the-log'], dateAdded: '2024-02-11' }`,
    `    { id: 'deck-110', name: 'Rainha Arqueira Miner Control', archetype: 'Control', winRate: 54.2, usageRate: 7.7, cards: ['archer-queen','miner','wall-breakers','magic-archer','valkyrie','bomb-tower','the-log','poison'], dateAdded: '2024-02-12' }`,
    `    { id: 'deck-111', name: 'Evo Valquíria Miner', archetype: 'Control', winRate: 53.6, usageRate: 8.0, cards: ['miner','valkyrie-ev1','magic-archer','bomb-tower','wall-breakers','the-log','arrows','ice-spirit'], dateAdded: '2024-02-13' }`,
    `    { id: 'deck-112', name: 'Cavaleiro Dourado Hog', archetype: 'Cycle', winRate: 55.4, usageRate: 10.4, cards: ['golden-knight','hog-rider','musketeer','ice-golem','cannon','ice-spirit','fireball','the-log'], dateAdded: '2024-02-14' }`,
    `    { id: 'deck-113', name: 'Rei Esqueleto LavaLoon', archetype: 'Beatdown', winRate: 56.7, usageRate: 4.4, cards: ['skeleton-king','lava-hound','balloon','mega-minion','skeleton-dragons','flying-machine','arrows','zap'], dateAdded: '2024-02-15' }`,
    `    { id: 'deck-114', name: 'Evo Arqueiras X-Bow', archetype: 'Siege', winRate: 51.5, usageRate: 5.3, cards: ['x-bow','archers-ev1','knight','skeletons','tesla','ice-spirit','fireball','the-log'], dateAdded: '2024-02-16' }`,
    `    { id: 'deck-115', name: 'Evo Rompedores Miner', archetype: 'Control', winRate: 53.0, usageRate: 7.5, cards: ['miner','wall-breakers-ev1','firecracker','goblin-gang','bomb-tower','the-log','arrows','ice-spirit'], dateAdded: '2024-02-17' }`,
    `    { id: 'deck-116', name: 'Pequeno Príncipe Elixir Golem', archetype: 'Beatdown', winRate: 57.0, usageRate: 3.9, cards: ['elixir-golem','little-prince','battle-healer','electro-dragon','night-witch','inferno-dragon','rage','zap'], dateAdded: '2024-02-18' }`,
    `    { id: 'deck-117', name: 'Monge Graveyard', archetype: 'Control', winRate: 54.5, usageRate: 6.8, cards: ['monk','graveyard','poison','tombstone','zappies','skeleton-dragons','barbarian-barrel','tornado'], dateAdded: '2024-02-19' }`,
    `    { id: 'deck-118', name: 'Evo Morteiro Spam', archetype: 'Siege', winRate: 50.5, usageRate: 5.1, cards: ['mortar-ev1','miner','bats','goblin-gang','spear-goblins','princess','the-log','fireball'], dateAdded: '2024-02-20' }`,
    `    { id: 'deck-119', name: 'Evo RG Fisherman', archetype: 'Control', winRate: 53.3, usageRate: 7.9, cards: ['royal-giant-ev1','fisherman','hunter','zappies','royal-ghost','electro-spirit','fireball','the-log'], dateAdded: '2024-02-21' }`,
    `    { id: 'deck-120', name: 'Rainha Arqueira Balloon', archetype: 'Aggro', winRate: 56.5, usageRate: 5.0, cards: ['archer-queen','balloon','lumberjack','inferno-dragon','bowler','freeze','tornado','barbarian-barrel'], dateAdded: '2024-02-22' }`,
    `    { id: 'deck-121', name: 'Evo Fogueteira Giant', archetype: 'Beatdown', winRate: 52.8, usageRate: 6.6, cards: ['giant','firecracker-ev1','musketeer','electro-wizard','mega-minion','zap','arrows','the-log'], dateAdded: '2024-02-23' }`,
    `    { id: 'deck-122', name: 'Pequeno Príncipe Miner Cycle', archetype: 'Cycle', winRate: 54.0, usageRate: 9.2, cards: ['miner','little-prince','wall-breakers','firecracker','goblin-gang','the-log','arrows','ice-spirit'], dateAdded: '2024-02-24' }`,
    `    { id: 'deck-123', name: 'Cavaleiro Dourado Splashyard', archetype: 'Control', winRate: 55.7, usageRate: 5.7, cards: ['golden-knight','graveyard','bowler','valkyrie','baby-dragon','tornado','poison','barbarian-barrel'], dateAdded: '2024-02-25' }`,
    `    { id: 'deck-124', name: 'Evo Bombardeiro Hog', archetype: 'Cycle', winRate: 51.9, usageRate: 9.5, cards: ['hog-rider','bomber-ev1','musketeer','cannon','ice-golem','skeletons','the-log','fireball'], dateAdded: '2024-02-26' }`,
    `    { id: 'deck-125', name: 'Monge Bridge Spam', archetype: 'Bridge Spam', winRate: 56.9, usageRate: 6.0, cards: ['monk','pekka','battle-ram','bandit','royal-ghost','magic-archer','zap','poison'], dateAdded: '2024-02-27' }`,
    `    { id: 'deck-126', name: 'Evo Goblins Lança Canhão', archetype: 'Cycle', winRate: 50.3, usageRate: 8.4, cards: ['hog-rider','spear-goblins-ev1','ice-spirit','musketeer','cannon','ice-golem','fireball','the-log'], dateAdded: '2024-02-28' }`,
    `    { id: 'deck-127', name: 'Rei Esqueleto Beatdown', archetype: 'Beatdown', winRate: 55.8, usageRate: 5.1, cards: ['skeleton-king','giant','musketeer','valkyrie','dark-prince','archers','arrows','fireball'], dateAdded: '2024-03-01' }`,
    `    { id: 'deck-128', name: 'Evo Recrutas Controle', archetype: 'Control', winRate: 52.5, usageRate: 7.0, cards: ['royal-recruits-ev1','zappies','goblin-cage','flying-machine','barbarian-barrel','royal-delivery','arrows','the-log'], dateAdded: '2024-03-02' }`,
    `    { id: 'deck-129', name: 'Rainha Arqueira Golem', archetype: 'Beatdown', winRate: 57.8, usageRate: 3.8, cards: ['archer-queen','golem','night-witch','lumberjack','mega-minion','baby-dragon','tornado','lightning'], dateAdded: '2024-03-03' }`,
    `    { id: 'deck-130', name: 'Evo Espírito Gelo Miner', archetype: 'Cycle', winRate: 53.5, usageRate: 9.6, cards: ['miner','ice-spirit-ev1','wall-breakers','magic-archer','bomb-tower','goblin-gang','the-log','poison'], dateAdded: '2024-03-04' }`,
    `    { id: 'deck-131', name: 'Mineiro Poderoso Graveyard', archetype: 'Control', winRate: 54.1, usageRate: 7.2, cards: ['mighty-miner','graveyard','poison','tombstone','valkyrie','baby-dragon','tornado','barbarian-barrel'], dateAdded: '2024-03-05' }`,
    `    { id: 'deck-132', name: 'Evo Gigante Goblin Witch', archetype: 'Beatdown', winRate: 53.9, usageRate: 4.9, cards: ['goblin-giant-ev1','witch','dark-prince','electro-wizard','baby-dragon','zap','arrows','fireball'], dateAdded: '2024-03-06' }`,
    `    { id: 'deck-133', name: 'Pequeno Príncipe RG', archetype: 'Beatdown', winRate: 52.0, usageRate: 6.2, cards: ['royal-giant','little-prince','electro-wizard','hunter','zappies','royal-ghost','fireball','the-log'], dateAdded: '2024-03-07' }`,
    `    { id: 'deck-134', name: 'Cavaleiro Dourado Mortar', archetype: 'Siege', winRate: 51.4, usageRate: 5.8, cards: ['mortar','golden-knight','miner','bats','goblin-gang','spear-goblins','the-log','fireball'], dateAdded: '2024-03-08' }`,
    `    { id: 'deck-135', name: 'Monge Elixir Golem', archetype: 'Beatdown', winRate: 56.4, usageRate: 4.0, cards: ['elixir-golem','monk','battle-healer','mega-minion','electro-dragon','inferno-dragon','rage','zap'], dateAdded: '2024-03-09' }`,
    `    { id: 'deck-136', name: 'Evo Bárbaros Hog', archetype: 'Cycle', winRate: 53.2, usageRate: 8.8, cards: ['hog-rider','barbarians-ev1','cannon','ice-golem','skeletons','ice-spirit','fireball','the-log'], dateAdded: '2024-03-10' }`,
    `    { id: 'deck-137', name: 'Rainha Arqueira Sparky', archetype: 'Beatdown', winRate: 55.0, usageRate: 5.3, cards: ['goblin-giant','sparky','archer-queen','dark-prince','electro-wizard','mega-minion','zap','lightning'], dateAdded: '2024-03-11' }`,
    `    { id: 'deck-138', name: 'Evo Cavaleiro Miner', archetype: 'Control', winRate: 53.7, usageRate: 7.9, cards: ['miner','knight-ev1','wall-breakers','magic-archer','firecracker','the-log','arrows','bomb-tower'], dateAdded: '2024-03-12' }`,
    `    { id: 'deck-139', name: 'Pequeno Príncipe LavaLoon', archetype: 'Beatdown', winRate: 57.2, usageRate: 3.7, cards: ['little-prince','lava-hound','balloon','mega-minion','skeleton-dragons','flying-machine','arrows','zap'], dateAdded: '2024-03-13' }`,
    `    { id: 'deck-140', name: 'Rei Esqueleto X-Bow', archetype: 'Siege', winRate: 51.6, usageRate: 6.3, cards: ['x-bow','skeleton-king','archers','knight','tesla','ice-spirit','fireball','the-log'], dateAdded: '2024-03-14' }`,
    `    { id: 'deck-141', name: 'Rainha Arqueira Splashyard', archetype: 'Control', winRate: 54.8, usageRate: 6.6, cards: ['archer-queen','graveyard','bowler','baby-dragon','ice-wizard','tornado','poison','barbarian-barrel'], dateAdded: '2024-03-15' }`,
    `    { id: 'deck-142', name: 'Evo Valquíria Hog', archetype: 'Cycle', winRate: 52.2, usageRate: 9.1, cards: ['hog-rider','valkyrie-ev1','musketeer','cannon','ice-golem','skeletons','fireball','the-log'], dateAdded: '2024-03-16' }`,
    `    { id: 'deck-143', name: 'Monge Ram Rider', archetype: 'Cycle', winRate: 53.4, usageRate: 5.0, cards: ['monk','ram-rider','magic-archer','royal-ghost','ice-golem','the-log','fireball','zap'], dateAdded: '2024-03-17' }`,
    `    { id: 'deck-144', name: 'Evo Rompedores Bridge Spam', archetype: 'Bridge Spam', winRate: 55.6, usageRate: 5.9, cards: ['pekka','wall-breakers-ev1','bandit','royal-ghost','magic-archer','electro-wizard','zap','poison'], dateAdded: '2024-03-18' }`,
    `    { id: 'deck-145', name: 'Cavaleiro Dourado Graveyard', archetype: 'Control', winRate: 55.2, usageRate: 6.7, cards: ['golden-knight','graveyard','poison','tombstone','zappies','skeleton-dragons','barbarian-barrel','tornado'], dateAdded: '2024-03-19' }`,
    `    { id: 'deck-146', name: 'Miner Evo Morteiro', archetype: 'Siege', winRate: 50.7, usageRate: 5.5, cards: ['mortar-ev1','miner','minion-horde','goblin-gang','spear-goblins','princess','the-log','fireball'], dateAdded: '2024-03-20' }`,
    `    { id: 'deck-147', name: 'Evo Morcegos LavaLoon', archetype: 'Beatdown', winRate: 57.6, usageRate: 3.6, cards: ['lava-hound','balloon','bats-ev1','mega-minion','skeleton-dragons','flying-machine','arrows','zap'], dateAdded: '2024-03-21' }`,
    `    { id: 'deck-148', name: 'Pequeno Príncipe Earthquake', archetype: 'Cycle', winRate: 54.3, usageRate: 10.0, cards: ['little-prince','hog-rider','earthquake','the-log','royal-delivery','cannon','skeletons','ice-spirit'], dateAdded: '2024-03-22' }`,
    `    { id: 'deck-149', name: 'Rei Esqueleto Balloon', archetype: 'Aggro', winRate: 55.4, usageRate: 5.4, cards: ['skeleton-king','balloon','lumberjack','freeze','inferno-dragon','electro-dragon','tornado','barbarian-barrel'], dateAdded: '2024-03-23' }`,
    `    { id: 'deck-150', name: 'Evo Fogueteira Ram Rider', archetype: 'Bridge Spam', winRate: 54.6, usageRate: 7.3, cards: ['ram-rider','firecracker-ev1','magic-archer','royal-ghost','ice-golem','the-log','fireball','zap'], dateAdded: '2024-03-24' }`,
    `    { id: 'deck-151', name: 'Rainha Arqueira LavaLoon', archetype: 'Beatdown', winRate: 57.9, usageRate: 3.5, cards: ['archer-queen','lava-hound','balloon','mega-minion','flying-machine','arrows','zap','tombstone'], dateAdded: '2024-03-25' }`,
    `    { id: 'deck-152', name: 'Monge Hog Earthquake', archetype: 'Cycle', winRate: 53.9, usageRate: 9.7, cards: ['monk','hog-rider','earthquake','firecracker','valkyrie','bomb-tower','skeletons','the-log'], dateAdded: '2024-03-26' }`,
    `    { id: 'deck-153', name: 'Evo Morcegos Bait', archetype: 'Bait', winRate: 52.4, usageRate: 8.6, cards: ['goblin-barrel','bats-ev1','princess','knight','inferno-tower','ice-spirit','the-log','rocket'], dateAdded: '2024-03-27' }`,
    `    { id: 'deck-154', name: 'Evo Esqueletos Hog', archetype: 'Cycle', winRate: 51.1, usageRate: 11.2, cards: ['hog-rider','skeletons-ev1','musketeer','ice-golem','cannon','ice-spirit','fireball','the-log'], dateAdded: '2024-03-28' }`,
    `    { id: 'deck-155', name: 'Cavaleiro Dourado LavaLoon', archetype: 'Beatdown', winRate: 57.7, usageRate: 3.4, cards: ['golden-knight','lava-hound','balloon','mega-minion','skeleton-dragons','flying-machine','arrows','zap'], dateAdded: '2024-03-29' }`,
    `    { id: 'deck-156', name: 'Pequeno Príncipe Golem Noturno', archetype: 'Beatdown', winRate: 56.1, usageRate: 5.2, cards: ['little-prince','golem','night-witch','lumberjack','baby-dragon','mega-minion','tornado','lightning'], dateAdded: '2024-03-30' }`,
    `    { id: 'deck-157', name: 'Mineiro Poderoso X-Bow', archetype: 'Siege', winRate: 51.2, usageRate: 6.1, cards: ['x-bow','mighty-miner','archers','knight','tesla','ice-spirit','fireball','the-log'], dateAdded: '2024-04-01' }`,
    `    { id: 'deck-158', name: 'Rei Esqueleto Bridge Spam', archetype: 'Bridge Spam', winRate: 56.3, usageRate: 6.4, cards: ['skeleton-king','pekka','battle-ram','bandit','magic-archer','royal-ghost','zap','poison'], dateAdded: '2024-04-02' }`,
    `    { id: 'deck-159', name: 'Evo RG Cycle', archetype: 'Cycle', winRate: 52.6, usageRate: 7.8, cards: ['royal-giant-ev1','electro-wizard','fisherman','zappies','royal-ghost','electro-spirit','fireball','the-log'], dateAdded: '2024-04-03' }`,
    `    { id: 'deck-160', name: 'Monge Graveyard Control', archetype: 'Control', winRate: 55.6, usageRate: 6.9, cards: ['monk','graveyard','bowler','valkyrie','baby-dragon','tornado','poison','barbarian-barrel'], dateAdded: '2024-04-04' }`,
    `    { id: 'deck-161', name: 'Evo Bárbaros Golem', archetype: 'Beatdown', winRate: 54.4, usageRate: 5.6, cards: ['golem','barbarians-ev1','baby-dragon','mega-minion','lumberjack','tornado','zap','lightning'], dateAdded: '2024-04-05' }`,
    `    { id: 'deck-162', name: 'Rainha Arqueira Log Bait', archetype: 'Bait', winRate: 55.5, usageRate: 8.0, cards: ['archer-queen','miner','goblin-barrel','princess','goblin-gang','inferno-tower','ice-spirit','the-log'], dateAdded: '2024-04-06' }`,
    `    { id: 'deck-163', name: 'Evo Cavaleiro LavaLoon', archetype: 'Beatdown', winRate: 56.8, usageRate: 4.1, cards: ['knight-ev1','lava-hound','balloon','mega-minion','flying-machine','arrows','zap','tombstone'], dateAdded: '2024-04-07' }`,
    `    { id: 'deck-164', name: 'Cavaleiro Dourado Earthquake Hog', archetype: 'Cycle', winRate: 55.0, usageRate: 10.6, cards: ['golden-knight','hog-rider','earthquake','the-log','royal-delivery','cannon','skeletons','ice-spirit'], dateAdded: '2024-04-08' }`,
    `    { id: 'deck-165', name: 'Pequeno Príncipe Bridge Spam', archetype: 'Bridge Spam', winRate: 57.4, usageRate: 5.7, cards: ['little-prince','pekka','battle-ram','bandit','magic-archer','royal-ghost','zap','poison'], dateAdded: '2024-04-09' }`,
    `    { id: 'deck-166', name: 'Evo Arqueiras Splashyard', archetype: 'Control', winRate: 52.1, usageRate: 8.1, cards: ['graveyard','archers-ev1','bowler','baby-dragon','valkyrie','tornado','poison','barbarian-barrel'], dateAdded: '2024-04-10' }`,
    `    { id: 'deck-167', name: 'Monge Balloon Freeze', archetype: 'Aggro', winRate: 56.2, usageRate: 5.3, cards: ['monk','balloon','lumberjack','freeze','bowler','inferno-dragon','electro-dragon','barbarian-barrel'], dateAdded: '2024-04-11' }`,
    `    { id: 'deck-168', name: 'Evo Fogueteira X-Bow', archetype: 'Siege', winRate: 51.8, usageRate: 5.9, cards: ['x-bow','firecracker-ev1','knight','skeletons','tesla','ice-spirit','fireball','the-log'], dateAdded: '2024-04-12' }`,
    `    { id: 'deck-169', name: 'Rei Esqueleto Miner', archetype: 'Control', winRate: 54.7, usageRate: 8.3, cards: ['skeleton-king','miner','wall-breakers','magic-archer','bomb-tower','goblin-gang','the-log','poison'], dateAdded: '2024-04-13' }`,
    `    { id: 'deck-170', name: 'Evo Gigante Goblin PEKKA', archetype: 'Beatdown', winRate: 54.1, usageRate: 4.7, cards: ['goblin-giant-ev1','pekka','electro-wizard','mega-minion','dark-prince','zap','lightning','arrows'], dateAdded: '2024-04-14' }`,
];

// Find the position right after the last deck line
const insertPos = lineEnd;
const before = content.slice(0, insertPos);
const after = content.slice(insertPos);

const newContent = before + ',\n' + newDecks.join(',\n') + after;
fs.writeFileSync('src/lib/mockData.js', newContent, 'utf8');
console.log('Done! Appended 100 decks with champions/evolutions.');
